// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `network.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include "network.h"
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

namespace
{

const ::std::string __vsm__network__VSClient__getClientType_name = "getClientType";

const ::std::string __vsm__network__VSServer__register_name = "register";

}

}

namespace
{

const char* __vsm__network__AlreadyConnectedException_name = "vsm::network::AlreadyConnectedException";

struct __F__vsm__network__AlreadyConnectedException : public ::IceInternal::UserExceptionFactory
{
    virtual void
    createAndThrow(const ::std::string&)
    {
        throw ::vsm::network::AlreadyConnectedException();
    }
};

class __F__vsm__network__AlreadyConnectedException__Init
{
public:

    __F__vsm__network__AlreadyConnectedException__Init()
    {
        ::IceInternal::factoryTable->addExceptionFactory("::vsm::network::AlreadyConnectedException", new __F__vsm__network__AlreadyConnectedException);
    }

    ~__F__vsm__network__AlreadyConnectedException__Init()
    {
        ::IceInternal::factoryTable->removeExceptionFactory("::vsm::network::AlreadyConnectedException");
    }
};

const __F__vsm__network__AlreadyConnectedException__Init __F__vsm__network__AlreadyConnectedException__i;

}

vsm::network::AlreadyConnectedException::AlreadyConnectedException(const ::std::string& __ice_reason) :
    ::Ice::UserException(),
    reason(__ice_reason)
{
}

vsm::network::AlreadyConnectedException::~AlreadyConnectedException() throw()
{
}

::std::string
vsm::network::AlreadyConnectedException::ice_name() const
{
    return __vsm__network__AlreadyConnectedException_name;
}

vsm::network::AlreadyConnectedException*
vsm::network::AlreadyConnectedException::ice_clone() const
{
    return new AlreadyConnectedException(*this);
}

void
vsm::network::AlreadyConnectedException::ice_throw() const
{
    throw *this;
}

void
vsm::network::AlreadyConnectedException::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice("::vsm::network::AlreadyConnectedException", -1, true);
    __os->write(reason);
    __os->endWriteSlice();
}

void
vsm::network::AlreadyConnectedException::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->read(reason);
    __is->endReadSlice();
}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::vsm::network::upCast(::IceProxy::vsm::network::VSClient* p) { return p; }

void
::IceProxy::vsm::network::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::vsm::network::VSClient>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::vsm::network::VSClient;
        v->__copyFrom(proxy);
    }
}

::vsm::network::ClientType
IceProxy::vsm::network::VSClient::getClientType(const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __vsm__network__VSClient__getClientType_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__vsm__network__VSClient__getClientType_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::vsm::network::VSClient* __del = dynamic_cast< ::IceDelegate::vsm::network::VSClient*>(__delBase.get());
            return __del->getClientType(__ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::vsm::network::VSClient::begin_getClientType(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__vsm__network__VSClient__getClientType_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __vsm__network__VSClient__getClientType_name, __del, __cookie);
    try
    {
        __result->__prepare(__vsm__network__VSClient__getClientType_name, ::Ice::Normal, __ctx);
        __result->__writeEmptyParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::vsm::network::ClientType
IceProxy::vsm::network::VSClient::end_getClientType(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __vsm__network__VSClient__getClientType_name);
    ::vsm::network::ClientType __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::vsm::network::VSClient::ice_staticId()
{
    return ::vsm::network::VSClient::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::vsm::network::VSClient::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::vsm::network::VSClient);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::vsm::network::VSClient::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::vsm::network::VSClient);
}

::IceProxy::Ice::Object*
IceProxy::vsm::network::VSClient::__newInstance() const
{
    return new VSClient;
}
::IceProxy::Ice::Object* ::IceProxy::vsm::network::upCast(::IceProxy::vsm::network::VSServer* p) { return p; }

void
::IceProxy::vsm::network::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::vsm::network::VSServer>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::vsm::network::VSServer;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::vsm::network::VSServer::_cpp_register(const ::vsm::network::VSClientPrx& client, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __vsm__network__VSServer__register_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__vsm__network__VSServer__register_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::vsm::network::VSServer* __del = dynamic_cast< ::IceDelegate::vsm::network::VSServer*>(__delBase.get());
            __del->_cpp_register(client, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::vsm::network::VSServer::begin_register(const ::vsm::network::VSClientPrx& client, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__vsm__network__VSServer__register_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __vsm__network__VSServer__register_name, __del, __cookie);
    try
    {
        __result->__prepare(__vsm__network__VSServer__register_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(client);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::vsm::network::VSServer::end_register(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __vsm__network__VSServer__register_name);
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::vsm::network::AlreadyConnectedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        __result->__readEmptyParams();
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::vsm::network::VSServer::ice_staticId()
{
    return ::vsm::network::VSServer::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::vsm::network::VSServer::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::vsm::network::VSServer);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::vsm::network::VSServer::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::vsm::network::VSServer);
}

::IceProxy::Ice::Object*
IceProxy::vsm::network::VSServer::__newInstance() const
{
    return new VSServer;
}

::vsm::network::ClientType
IceDelegateM::vsm::network::VSClient::getClientType(const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __vsm__network__VSClient__getClientType_name, ::Ice::Normal, __context, __observer);
    __og.writeEmptyParams();
    bool __ok = __og.invoke();
    ::vsm::network::ClientType __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateM::vsm::network::VSServer::_cpp_register(const ::vsm::network::VSClientPrx& client, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __vsm__network__VSServer__register_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(client);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::vsm::network::AlreadyConnectedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        __og.readEmptyParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::vsm::network::ClientType
IceDelegateD::vsm::network::VSClient::getClientType(const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::vsm::network::ClientType& __result, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::vsm::network::VSClient* servant = dynamic_cast< ::vsm::network::VSClient*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->getClientType(_current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::vsm::network::ClientType& _result;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __vsm__network__VSClient__getClientType_name, ::Ice::Normal, __context);
    ::vsm::network::ClientType __result;
    try
    {
        _DirectI __direct(__result, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

void
IceDelegateD::vsm::network::VSServer::_cpp_register(const ::vsm::network::VSClientPrx& client, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::vsm::network::VSClientPrx& __p_client, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_client(__p_client)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::vsm::network::VSServer* servant = dynamic_cast< ::vsm::network::VSServer*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            try
            {
                servant->_cpp_register(_m_client, _current);
                return ::Ice::DispatchOK;
            }
            catch(const ::Ice::UserException& __ex)
            {
                setUserException(__ex);
                return ::Ice::DispatchUserException;
            }
        }
        
    private:
        
        const ::vsm::network::VSClientPrx& _m_client;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __vsm__network__VSServer__register_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(client, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::vsm::network::AlreadyConnectedException&)
    {
        throw;
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* vsm::network::upCast(::vsm::network::VSClient* p) { return p; }

namespace
{
const ::std::string __vsm__network__VSClient_ids[2] =
{
    "::Ice::Object",
    "::vsm::network::VSClient"
};

}

bool
vsm::network::VSClient::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__vsm__network__VSClient_ids, __vsm__network__VSClient_ids + 2, _s);
}

::std::vector< ::std::string>
vsm::network::VSClient::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__vsm__network__VSClient_ids[0], &__vsm__network__VSClient_ids[2]);
}

const ::std::string&
vsm::network::VSClient::ice_id(const ::Ice::Current&) const
{
    return __vsm__network__VSClient_ids[1];
}

const ::std::string&
vsm::network::VSClient::ice_staticId()
{
    return __vsm__network__VSClient_ids[1];
}

::Ice::DispatchStatus
vsm::network::VSClient::___getClientType(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::vsm::network::ClientType __ret = getClientType(__current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __vsm__network__VSClient_all[] =
{
    "getClientType",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
vsm::network::VSClient::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__vsm__network__VSClient_all, __vsm__network__VSClient_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __vsm__network__VSClient_all)
    {
        case 0:
        {
            return ___getClientType(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
vsm::network::VSClient::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
vsm::network::VSClient::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
vsm::network::__patch(VSClientPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::vsm::network::VSClientPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::vsm::network::VSClient::ice_staticId(), v);
    }
}

::Ice::Object* vsm::network::upCast(::vsm::network::VSServer* p) { return p; }
::Ice::ObjectPtr
vsm::network::VSServer::ice_clone() const
{
    throw ::Ice::CloneNotImplementedException(__FILE__, __LINE__);
    return 0; // to avoid a warning with some compilers
}

namespace
{
const ::std::string __vsm__network__VSServer_ids[3] =
{
    "::Ice::Object",
    "::vsm::VSObject",
    "::vsm::network::VSServer"
};

}

bool
vsm::network::VSServer::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__vsm__network__VSServer_ids, __vsm__network__VSServer_ids + 3, _s);
}

::std::vector< ::std::string>
vsm::network::VSServer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__vsm__network__VSServer_ids[0], &__vsm__network__VSServer_ids[3]);
}

const ::std::string&
vsm::network::VSServer::ice_id(const ::Ice::Current&) const
{
    return __vsm__network__VSServer_ids[2];
}

const ::std::string&
vsm::network::VSServer::ice_staticId()
{
    return __vsm__network__VSServer_ids[2];
}

::Ice::DispatchStatus
vsm::network::VSServer::___register(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::vsm::network::VSClientPrx client;
    __is->read(client);
    __inS.endReadParams();
    try
    {
        _cpp_register(client, __current);
        __inS.__writeEmptyParams();
        return ::Ice::DispatchOK;
    }
    catch(const ::vsm::network::AlreadyConnectedException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

namespace
{
const ::std::string __vsm__network__VSServer_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "register"
};

}

::Ice::DispatchStatus
vsm::network::VSServer::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__vsm__network__VSServer_all, __vsm__network__VSServer_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __vsm__network__VSServer_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___register(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
vsm::network::VSServer::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, false);
    __os->endWriteSlice();
    ::vsm::VSObject::__writeImpl(__os);
}

void
vsm::network::VSServer::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
    ::vsm::VSObject::__readImpl(__is);
}

void 
vsm::network::__patch(VSServerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::vsm::network::VSServerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::vsm::network::VSServer::ice_staticId(), v);
    }
}
